### ISSUE TITLE
Monad implementation

### ISSUE THREAD

**Issue by rjmk** [joneshf/ziparray#1] opened 2016-05-28 13:33 UTC
This is very cool.

I was wondering what your thought process was when deciding whether to add further instances to this type. I'm guessing the idea is that you should just reach into the `ZipArray` with `runZipArray` and then rezip?

(Also, I'm not sure that `ZipArray#map` is lawful as it dispatches to `Array#map` which isn't lawful.

``` js
const f = R.curry((a, b) => a + b)

const xs = ZipArray([1,3,4])

!equivalent(xs.map(x => String(f(x))), xs.map(f).map(String))
```

But then, depending on how one parses the references to functions in the `Apply#ap` spec the `ap` might not be to spec either)

**Comment by joneshf** [comment] 2016-05-28 15:33
Wow, great catches! I'll make issues to track fixing those implementations.

Shooting for `Monad` requires some thought.

The first concern is `Applicative`. In order to be lawful, the implementation would need to change. Looking at the `identity` law, we need `a.of(x => x).ap(v) == v`, So when we implement `of`, we can't follow in `Array`s footsteps.

``` js
ZipArray.of = x => ZipArray([x]);
```

will only work if `v` is a singleton `ZipArray` to begin with. With the above implementation, we get behavior like this:

``` js
ZipArray.of(x => x).ap(ZipArray([1,2,3])) //=> ZipArray([1])
```

If the implementation is made lazy, then `of` can be a sort of "generator"  or "stream" function of a single value. so we would have a lawful implementation again. Something like:

``` js
ZipArray.of = x => Cons(x, () => ZipArray.of(x));
```

along with an implementation of `map` and `ap` that work with the laziness. Then we would have:

``` js
ZipArray.of(x => x).ap(ZipArray([1,2,3])) //=> ZipArray([1,2,3])
```

as we expect.

The second concern is `Chain`. The naive approach follows `Array`s implementation, which satisfies the `associativity` law. This implementation will not allow you to build upon it to make `Monad`, as the `identity` laws will then be unlawful. If we aim to make the `Monad` laws pass, then we'll break the `Chain` laws. Near as I can tell, there's no way to get a `Monad` for `ZipArray`. [Many](https://mail.haskell.org/pipermail/haskell-cafe/2009-April/059079.html) [people](https://mail.haskell.org/pipermail/haskell-cafe/2013-October/111004.html) [have](https://www.reddit.com/r/haskell/comments/nfyvy/instance_monad_ziplist_where/) [tried](http://www.ii.uni.wroc.pl/~dabi/courses/ZPF15/scielemecki/applicative-functors-homework.pdf) [though](http://www.xanthir.com/b4fM0).

The conclusion is, `Applicative` and `Chain` can be added, but `Monad` can not.

**Comment by rjmk** [comment] 2016-05-29 22:02
Those links were awesome! Thanks for sharing the knowledge :)

**Comment by joneshf** [comment] 2016-08-27 13:33
Closing since other issues are tracking concerns.

**Closed as completed by joneshf** 2016-08-27 13:33 UTC

**Comment by masaeedu** [comment] 2018-05-09 19:46
I think a `ZipArray` is a representable functor: i.e. `ZipArray x` is isomorphic to `Integer -> x`. This means you can just steal both the applicative and monad instance from that. The `Applicative` instance for functions is `Fn.const`, i.e. ignoring the integer passed in, always return the same value, which when translated through the isomorphism results in the same thing you have, i.e. an infinite list with the same value at every position. The monad instance for `Integer -> x` functions translated through the isomorphism may or may not make sense, but we can certainly try it out.

**Comment by masaeedu** [comment] 2018-05-09 21:02
@joneshf Here's an example of using the bounded function representation of an iterable to get the applicative instance for free: https://runkit.com/masaeedu/5af367065bba29001268d667

```js
// We don't have an instance of applicative for arrays that corresponds to zipping

// However, we can create one without ever talking about arrays at all, with most
// of the methods just stolen from the applicative instance for functions

// Implement applicative for functions over a bounded domain of natural numbers
// type BoundedFn x = { length :: Nat, fn :: Nat -> x }
const BoundedFn = (() => {
  // Notice how most of the implementations boil down to Fn.<same method>
  const of = x => ({ length: Infinity, fn: Fn.of(x) })
  const map = f => x => ({ length: x.length, fn: Fn.map(f)(x.fn) })
  const lift2 = f => x => y => ({ length: Math.min(x.length, y.length), fn: Fn.lift2(f)(x.fn)(y.fn) })

  return { of, map, lift2 }
})()

// We just need to provide a way to convert from arrays to bounded
// functions and back
const IsoArrBoundedFn = (() => {
  const from = ({ fn, length }) => Arr.map(fn)(Arr.range(length))

  const to = arr => ({ length: arr.length, fn: i => arr[i] })

  return { from, to }
})()

// destructure for convenience
const { from, to } = IsoArrBoundedFn

// tests
console.log([
  from(BoundedFn.lift2(x => y => x + y)(to([1, 2]))(to([4, 5, 6]))),
  // => [5, 7]
  from(Obj.sequence(BoundedFn)({ bar: to([4, 5]), foo: to([1, 2, 3]) }))
  // => [{ bar: 4, foo: 1 }, { bar: 5, foo: 2 }]
])
```

I actually ended up realizing that you can't safely get a monad instance from the bounded function representation; the problem is that the domain's length is inaccessible in `chain`.

**Comment by joneshf** [comment] 2018-05-10 00:15
Interesting, I'm going to look into this later

**Comment by masaeedu** [comment] 2018-05-10 02:17
The concept also generalizes to "ZipObjects": https://runkit.com/masaeedu/5af3653272d1d700129053ea

```
  from(Obj.sequence(EnumeratedFn)({ a: to({ x: 10, y: 11 }), b: to({ x: 22 }) })),
  // => { x: { a: 10, b: 22 } }
```
